import { describe, it, expect, vi } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { MhlbClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/health.js';
import type { MhlbConfig } from '../src/config.js';

/**
 * A CloudFront WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * Before mcp-utils 2.9.0 a CDN/WAF refusal read as a bad sign-in. Here it was
 * worse than the default: the sign-in path wraps any non-2xx token response as
 * "rejected the sign-in", which `classifyMhlbError` maps to
 * `credential_rejected` — sending the user to check a password on an account
 * that LOCKS on failed attempts — and the probe's own 403 was reported as a
 * role mismatch with the page dropped.
 *
 * These run the REAL client against the page CloudFront serves, so they fail
 * if anything between the response and the healthcheck drops what the shared
 * classifier reads.
 */

const CONFIG: MhlbConfig = {
  baseUrl: 'https://ordernow.myhotlunchbox.com',
  username: 'parent@example.com',
  password: 'pw',
};

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  'Request blocked. We can\'t connect to the server for this app or website at this time. ' +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  });
}

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

const TOKEN = { access_token: 'access-1', refresh_token: 'refresh-1', expires_in: 3600 };

const isLogin = (url: string): boolean => url.endsWith('/api/auth/login');

interface Result {
  ok: boolean;
  error?: { kind: string; message: string; detail?: Record<string, unknown> };
  hint: string;
}

async function healthcheck(client: MhlbClient): Promise<Result> {
  const harness = await createTestHarness((s) => registerHealthcheckTools(s, client, () => CONFIG));
  return parseToolResult<Result>(await harness.callTool('mhlb_healthcheck'));
}

describe('a CloudFront block reads as edge_blocked, not a rejected credential', () => {
  it('on the sign-in the probe triggers', async () => {
    const fetchImpl = vi.fn(async () => blocked());

    const r = await healthcheck(new MhlbClient(CONFIG, fetchImpl as unknown as typeof fetch));

    expect(fetchImpl).toHaveBeenCalled();
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail?.vendor).toBe('CloudFront');
    // The copy that sent the user to check a password on a locking account
    // must not be what they read.
    expect(r.hint).not.toMatch(/rejected the sign-in|Check MYHOTLUNCHBOX_USERNAME/);
    expect(r.hint).toMatch(/CDN\/WAF/);
  });

  it('on the probe itself, after a good sign-in', async () => {
    const fetchImpl = vi.fn(async (url: string) => (isLogin(url) ? json(200, TOKEN) : blocked()));

    const r = await healthcheck(new MhlbClient(CONFIG, fetchImpl as unknown as typeof fetch));

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail?.vendor).toBe('CloudFront');
    // Not the role-mismatch copy a genuine 403 from the API gets.
    expect(r.error?.message).not.toMatch(/not available to a parent account/);
  });

  it('a blocked sign-in does not latch the credential as rejected', async () => {
    let block = true;
    const fetchImpl = vi.fn(async (url: string) => {
      if (block) return blocked();
      return isLogin(url) ? json(200, TOKEN) : json(200, { email: 'parent@example.com' });
    });
    const client = new MhlbClient(CONFIG, fetchImpl as unknown as typeof fetch);

    expect((await healthcheck(client)).error?.kind).toBe('edge_blocked');
    block = false;

    // The block lifted: the next call signs in again rather than replaying a
    // latched "rejected" error that needs mhlb_session_reset to clear.
    expect((await healthcheck(client)).ok).toBe(true);
  });

  it("control: an invalid_grant from the token endpoint is still a rejected credential", async () => {
    const fetchImpl = vi.fn(async () =>
      json(400, { error: 'invalid_grant', error_description: 'The user name or password is incorrect.' }),
    );

    const r = await healthcheck(new MhlbClient(CONFIG, fetchImpl as unknown as typeof fetch));

    expect(r.error?.kind).toBe('credential_rejected');
  });

  it("control: the API's own 403 is not called an edge block", async () => {
    const fetchImpl = vi.fn(async (url: string) =>
      isLogin(url) ? json(200, TOKEN) : json(403, { message: 'Forbidden' }),
    );

    const err = await new MhlbClient(CONFIG, fetchImpl as unknown as typeof fetch)
      .get('/auth/userinfo')
      .catch((e: unknown) => e);

    expect((err as Error).message).toMatch(/refused GET \/auth\/userinfo \(HTTP 403\)/);
    expect((err as Error).name).not.toBe('EdgeBlockedError');
  });
});
